//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCustomTablesDesignerExtension {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleCustomTablesDesignerExtension.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom link label.
        /// </summary>
        public static string BottomLinkLabel {
            get {
                return ResourceManager.GetString("BottomLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button hide.
        /// </summary>
        public static string ButtonHide {
            get {
                return ResourceManager.GetString("ButtonHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button text.
        /// </summary>
        public static string ButtonText {
            get {
                return ResourceManager.GetString("ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button url.
        /// </summary>
        public static string ButtonUrl {
            get {
                return ResourceManager.GetString("ButtonUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget / Personal account folder.
        /// </summary>
        public static string ControlTypes_PersonalAccountFolderDashboardWidget {
            get {
                return ResourceManager.GetString("ControlTypes_PersonalAccountFolderDashboardWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter hide.
        /// </summary>
        public static string CounterHide {
            get {
                return ResourceManager.GetString("CounterHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomCssClasses.
        /// </summary>
        public static string CustomCssClasses {
            get {
                return ResourceManager.GetString("CustomCssClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table hide.
        /// </summary>
        public static string TableHide {
            get {
                return ResourceManager.GetString("TableHide", resourceCulture);
            }
        }
    }
}
